apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-worker
  template:
    metadata:
      labels:
        app: backend-worker
    spec:
      restartPolicy: Always
      containers:
        - name: backend-worker
          image: rajlodhi09/backend-worker:bc66528c920c1485b3092b0fc23a00e43a6afb5b
          imagePullPolicy: Always
