apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-worker
  template:
    metadata:
      labels:
        app: backend-worker
    spec:
      restartPolicy: Always
      containers:
        - name: backend-worker
          image: rajlodhi09/backend-worker:SHA_H
          imagePullPolicy: Always
