apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: rajlodhi09/node-app:0b15a2ec8465666c560ff6d5482a6bc9ae0de0a3
          ports:
            - containerPort: 3000
